version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: milk-management-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: milk-management-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    command: [ "start-dev" ]
    depends_on:
      - postgres
    networks:
      - keycloak-network

volumes:
  postgres_data:


networks:
  keycloak-network:
