export const keycloakExceptions = {
  'The content-type header value did not match the value in @Consumes': 'o payload fornecido não é do tipo esperado!',
  'Request failed with status code 409': 'os dados inserido já podem ter sido cadastrados!',
  'User exists with same email': 'Já existe um usuário cadastrado com esse email!',
  'connect ECONNREFUSED ::1:8080': 'não foi possível se conectar ao autenticador',
  'Could not find role with id': 'não foram encontradas roles com esse id!',
  'HTTP 404 Not Found': 'os recursos solicitados não foram encontrados!',
  'Could not find role': 'não foram encontradas roles com esse nome!',
  'Could not find group by id': 'não foi encontrado nenhum grupo!',
  'Role not found': 'não foram encontradas roles com esse nome!',
  Conflict: 'os dados inseridos já podem ter sido cadastrados!',
  unknown_error: 'os parâmetros enviados não parecem certos!',
  ECONNREFUSED: 'a conexão com o autenticador foi recusada!',
  ERR_BAD_REQUEST: 'alguns parâmetros não foram fornecidos!',
  EAI_AGAIN: 'a conexão com o autenticador foi recusada!',
  'HTTP 401 Unauthorized': 'usuário não autorizado!',
  'HTTP 403 Forbidden': 'usuário sem as permissões!',
  unauthorized_client: 'cliente não autorizado!',
  default: 'erro desconhecido no autenticador!',
  'Client not found': 'cliente não encontrado!',
  invalid_grant: 'usuário ou senha inválidos!',
  invalid_client: 'usuário não autorizado!',
  Unauthorized: 'usuário não autorizado!',
  'Not Found': 'recurso não encontrado!',
};
