name: deploy to lambda
on: [push]
jobs:
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      # Checkout do código-fonte
      - name: Checkout source code
        uses: actions/checkout@v1

      # Configuração do Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalação das dependências
      - name: Install dependencies
        run: npm install

      # Gerar o arquivo ZIP para implantação
      - name: Generate ZIP
        run: |
          zip -r deployment.zip *
          ls -lh deployment.zip

      # Verificar se o arquivo ZIP foi gerado
      - name: Verify ZIP existence
        run: |
          if [ ! -f "deployment.zip" ]; then
            echo "Error: deployment.zip not found."
            exit 1
          fi

      # Fazer upload do arquivo ZIP para o S3
      - name: Upload ZIP to S3
        run: |
          aws s3 cp deployment.zip s3://${{ secrets.S3_BUCKET_NAME }}/deployment.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      # Atualizar a função Lambda com o arquivo do S3
      - name: Update Lambda function from S3
        run: |
          aws lambda update-function-code \
            --function-name milk-erp-api \
            --s3-bucket ${{ secrets.S3_BUCKET_NAME }} \
            --s3-key deployment.zip \
            --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}