name: deploy to lambda
on: [push]
jobs:
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
      # Checkout do código-fonte
      - name: Checkout source code
        uses: actions/checkout@v1

      # Configuração do Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalação das dependências
      - name: Install dependencies
        run: npm install

      # Gerar o arquivo ZIP para implantação
      - name: Generate ZIP
        run: |
          zip -r deployment.zip *
          echo "Generated ZIP file:"
          ls -lh deployment.zip

      # Verificar se o arquivo ZIP foi gerado
      - name: Verify ZIP existence
        run: |
          if [ ! -f "deployment.zip" ]; then
            echo "Error: deployment.zip not found."
            exit 1
          fi

      # Fazer upload do arquivo ZIP para o S3 usando a ação `s3-zip-upload`
      - name: Upload ZIP to S3
        uses: NotCoffee418/s3-zip-upload@v1.5
        with:
          aws-secret-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucket-name: ${{ secrets.S3_BUCKET_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}
          source-mode: ZIP
          source-path: ./deployment.zip
          dest-file: deployment.zip
          content-type: application/zip

      # Atualizar a função Lambda com o arquivo do S3
      - name: Update Lambda function from S3
        run: |
          aws lambda update-function-code \
            --function-name milk-erp-api \
            --s3-bucket ${{ secrets.S3_BUCKET_NAME }} \
            --s3-key deployment.zip \
            --region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
